config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # get '/ask', to: 'questions_controller#ask'

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'questions#home'
  get 'ask', to: 'questions#ask'
  get 'answer', to: 'questions#answer'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def ask
  end

  def answer
    @question = params[:question]
    if @question.include?('!')
      @answer = 'Great!'
    elsif @question.include?('?')
      @answer = 'Silly question, get dressed and go to work!'
    else
      @answer = "I don't care, get dressed and go to work!"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/answer.html.erb
<h1>Stupid Coaching</h1>

<div class="container bg-light p-5">
  <h2>Your question</h2>
  <p><%= @question %></p>

  <h2>Your coach's answer</h2>
  <p><%= @answer %></p>

  <%= link_to "Ask a new question", ask_path %>
</div>

app/views/questions/ask.html.erb
<div class="container bg-light p-5">
  <h1 class="text-center mb-6">What's your questions?</h1>
  <form class="form-control d-flex justify-content-center" action="/answer" data-turbo="false">
    <input class="rounded w-100" type="text" name="question" value=<% params[:querry] %>>
    <input type="submit" value="Ask!" class="btn btn-primary">
  </form>
</div>
<div class="d-flex justify-content-center">
<p>Ask your coach anything</p>
  <%= link_to "Let's get some more motivation", answer_path %>
</div>